version: '2'
services:
  mysql:
    image: mariadb
    restart: always
    container_name: mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'hello_world'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'project-zero'
